import { db, jobOpenings, type NewJobOpening } from "@workspace/db";
import { and, eq } from "drizzle-orm";
import { logger } from "./logger";

const JOBS: NewJobOpening[] = [
  {
    titleAr: "مستشار نظم إسلامية أول",
    titleEn: "Senior Shariah Governance & Compliance Systems Consultant",
    deptAr: "الاستشارات",
    deptEn: "Consulting",
    locationAr: "القاهرة، مصر",
    locationEn: "Cairo, Egypt",
    type: "full-time",
    typeAr: "دوام كامل",
    typeEn: "Full-time",
    posted: "2026-04-01",
    remote: false,
    descAr: "نبحث عن مستشار متخصص في أنظمة الحوكمة والامتثال الشرعي والحوكمة الشرعية لخدمة عملائنا من المؤسسات والحكومات.",
    descEn: "We are looking for a specialist in Islamic systems and Sharia governance to serve our institutional and government clients.",
    skillsAr: ["الفقه الإسلامي", "الحوكمة الشرعية", "الاستشارات المؤسسية"],
    skillsEn: ["Islamic Jurisprudence", "Sharia Governance", "Institutional Consulting"],
    category: "consulting",
    status: "active",
  },
  {
    titleAr: "متخصص نظم إدارية",
    titleEn: "Management Systems Specialist",
    deptAr: "الاستشارات",
    deptEn: "Consulting",
    locationAr: "عن بُعد",
    locationEn: "Remote",
    type: "full-time",
    typeAr: "دوام كامل",
    typeEn: "Full-time",
    posted: "2026-04-03",
    remote: true,
    descAr: "انضم إلى فريقنا لتطوير النظم الإدارية وأطر الحوكمة لعملائنا في القطاعين العام والخاص.",
    descEn: "Join our team to develop management systems and governance frameworks for clients in both public and private sectors.",
    skillsAr: ["الإدارة الاستراتيجية", "إدارة الأداء", "تطوير السياسات"],
    skillsEn: ["Strategic Management", "Performance Management", "Policy Development"],
    category: "consulting",
    status: "active",
  },
  {
    titleAr: "محلل تحول رقمي",
    titleEn: "Digital Transformation Analyst",
    deptAr: "التحول الرقمي",
    deptEn: "Digital",
    locationAr: "الرياض، المملكة العربية السعودية",
    locationEn: "Riyadh, Saudi Arabia",
    type: "full-time",
    typeAr: "دوام كامل",
    typeEn: "Full-time",
    posted: "2026-04-05",
    remote: false,
    descAr: "قُد مبادرات التحول الرقمي لدى عملائنا، بدءاً من تقييم النضج الرقمي وحتى تنفيذ الحلول التقنية.",
    descEn: "Lead digital transformation initiatives for our clients, from digital maturity assessments to technology solution implementation.",
    skillsAr: ["التحول الرقمي", "إدارة المشاريع", "تحليل البيانات"],
    skillsEn: ["Digital Transformation", "Project Management", "Data Analysis"],
    category: "digital",
    status: "active",
  },
  {
    titleAr: "مدير برامج منتجات الذكاء الاصطناعي",
    titleEn: "AI Products Program Manager",
    deptAr: "التحول الرقمي",
    deptEn: "Digital",
    locationAr: "القاهرة، مصر",
    locationEn: "Cairo, Egypt",
    type: "full-time",
    typeAr: "دوام كامل",
    typeEn: "Full-time",
    posted: "2026-04-07",
    remote: false,
    descAr: "أدِر تطوير منتجات الذكاء الاصطناعي لمنصة وكيل الاستشارات الذكي وتوسيع نطاقها.",
    descEn: "Manage the development and scaling of AI products for our intelligent consulting agent platform.",
    skillsAr: ["إدارة المنتجات", "الذكاء الاصطناعي", "البرمجة"],
    skillsEn: ["Product Management", "Artificial Intelligence", "Software Engineering"],
    category: "digital",
    status: "active",
  },
  {
    titleAr: "مدير برامج أكاديمية",
    titleEn: "Academy Program Manager",
    deptAr: "الأكاديمية",
    deptEn: "Academy",
    locationAr: "القاهرة، مصر",
    locationEn: "Cairo, Egypt",
    type: "full-time",
    typeAr: "دوام كامل",
    typeEn: "Full-time",
    posted: "2026-03-28",
    remote: false,
    descAr: "صمّم وأدِر البرامج التدريبية والأكاديمية المتخصصة في أنظمة الحوكمة والامتثال الشرعي والإدارية.",
    descEn: "Design and manage specialized training and academic programs in Islamic and management systems.",
    skillsAr: ["التصميم التعليمي", "إدارة البرامج", "التدريب"],
    skillsEn: ["Instructional Design", "Program Management", "Training"],
    category: "academy",
    status: "active",
  },
  {
    titleAr: "مدرب معتمد — القيادة والحوكمة",
    titleEn: "Certified Trainer — Leadership & Governance",
    deptAr: "الأكاديمية",
    deptEn: "Academy",
    locationAr: "عن بُعد",
    locationEn: "Remote",
    type: "part-time",
    typeAr: "دوام جزئي",
    typeEn: "Part-time",
    posted: "2026-04-02",
    remote: true,
    descAr: "قدّم برامج تدريبية متخصصة في القيادة المؤسسية والحوكمة لعملائنا من المديرين والمسؤولين.",
    descEn: "Deliver specialized training programs in institutional leadership and governance for our executive and leadership clients.",
    skillsAr: ["التدريب", "القيادة", "الحوكمة"],
    skillsEn: ["Training", "Leadership", "Governance"],
    category: "academy",
    status: "active",
  },
  {
    titleAr: "مدير البحث والنشر",
    titleEn: "Research & Publishing Director",
    deptAr: "البحث والنشر",
    deptEn: "Research",
    locationAr: "القاهرة، مصر",
    locationEn: "Cairo, Egypt",
    type: "full-time",
    typeAr: "دوام كامل",
    typeEn: "Full-time",
    posted: "2026-03-25",
    remote: false,
    descAr: "قُد فريق البحث العلمي والنشر المتخصص في تأليف وترجمة الكتب الإدارية والشرعية.",
    descEn: "Lead the research and publishing team specializing in authoring and translating management and Sharia books.",
    skillsAr: ["البحث العلمي", "النشر", "التحرير"],
    skillsEn: ["Scientific Research", "Publishing", "Editing"],
    category: "research",
    status: "active",
  },
  {
    titleAr: "محرر محتوى وترجمة",
    titleEn: "Content Editor & Translator",
    deptAr: "البحث والنشر",
    deptEn: "Research",
    locationAr: "عن بُعد",
    locationEn: "Remote",
    type: "part-time",
    typeAr: "دوام جزئي",
    typeEn: "Part-time",
    posted: "2026-04-06",
    remote: true,
    descAr: "أنتج محتوى أكاديمياً عالي الجودة وترجم المحتوى العلمي بين العربية والإنجليزية.",
    descEn: "Produce high-quality academic content and translate scientific content between Arabic and English.",
    skillsAr: ["الكتابة الأكاديمية", "الترجمة", "التدقيق اللغوي"],
    skillsEn: ["Academic Writing", "Translation", "Proofreading"],
    category: "research",
    status: "active",
  },
  {
    titleAr: "مدير تطوير الأعمال",
    titleEn: "Business Development Manager",
    deptAr: "الإدارة",
    deptEn: "Management",
    locationAr: "دبي، الإمارات العربية المتحدة",
    locationEn: "Dubai, UAE",
    type: "full-time",
    typeAr: "دوام كامل",
    typeEn: "Full-time",
    posted: "2026-04-04",
    remote: false,
    descAr: "طوّر استراتيجيات النمو وأدِر علاقات العملاء وافتح أسواقاً جديدة في منطقة الخليج.",
    descEn: "Develop growth strategies, manage client relationships, and open new markets across the Gulf region.",
    skillsAr: ["تطوير الأعمال", "إدارة العلاقات", "التفاوض"],
    skillsEn: ["Business Development", "Relationship Management", "Negotiation"],
    category: "management",
    status: "active",
  },
  {
    titleAr: "مستشار حوكمة — القطاع الحكومي",
    titleEn: "Governance Consultant — Government Sector",
    deptAr: "الاستشارات",
    deptEn: "Consulting",
    locationAr: "أبوظبي، الإمارات",
    locationEn: "Abu Dhabi, UAE",
    type: "full-time",
    typeAr: "دوام كامل",
    typeEn: "Full-time",
    posted: "2026-03-30",
    remote: false,
    descAr: "قدّم خدمات الاستشارات الحوكمية للجهات الحكومية وساعدها في تطوير سياساتها وأنظمتها المؤسسية.",
    descEn: "Provide governance consulting services to government entities and help them develop their institutional policies and systems.",
    skillsAr: ["الحوكمة", "السياسات العامة", "القطاع الحكومي"],
    skillsEn: ["Governance", "Public Policy", "Government Sector"],
    category: "consulting",
    status: "active",
  },
];

export async function seedJobOpenings(
  options: { throwOnError?: boolean } = {},
): Promise<void> {
  try {
    let inserted = 0;
    let skipped = 0;
    for (const job of JOBS) {
      const existing = await db
        .select({ id: jobOpenings.id })
        .from(jobOpenings)
        .where(
          and(
            eq(jobOpenings.titleAr, job.titleAr),
            eq(jobOpenings.titleEn, job.titleEn),
          ),
        )
        .limit(1);
      if (existing.length > 0) {
        skipped++;
        continue;
      }
      await db.insert(jobOpenings).values(job);
      inserted++;
    }
    logger.info(
      { inserted, skipped, total: JOBS.length },
      "Job openings seeded",
    );
  } catch (err) {
    logger.error({ err }, "Failed to seed job openings");
    if (options.throwOnError) throw err;
  }
}
